name: Continuous Integration

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Build and test
      run: |
        docker build -t my_app .
        docker run my_app pytest

    - name: Push to container registry
      run: |
        docker tag my_app my_container_registry/my_app:${{ github.sha }}
        docker push my_container_registry/my_app:${{ github.sha }}
